name: release-main

on:
  release:
    types: [published]
    branches: [main]

jobs:

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up the environment
        uses: ./.github/actions/setup-poetry-env

      - name: Deploy documentation
        run: poetry run mkdocs -f ./mkdocs-build.yml gh-deploy --force
